CREATE TABLE TAB_CLIENTE (
    ID_CLIENTE INT CONSTRAINT TAB_CLIENTE_PK PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(100)
);
/
CREATE TABLE TAB_PRODUTO (
    ID_PRODUTO INT CONSTRAINT TAB_PRODUTO_PK PRIMARY KEY,
    NOME_PRODUTO VARCHAR2(100),
    VALOR_PRODUTO NUMBER
);
/
CREATE TABLE TAB_PEDIDO (
    ID_PEDIDO INT CONSTRAINT TAB_PEDIDO_PK PRIMARY KEY,
    ID_CLIENTE INT, 
    ID_PRODUTO INT, 
    DATA_PEDIDO DATE, 
    QT_PRODUTO INT

)