SELECT TAB_CLIENTE.NOME_CLIENTE, SUM(TAB_PEDIDO.QT_PRODUTO)
FROM TAB_CLIENTE
ON TAB_CLIENTE.ID_CLIENTE = TAB_PEDIDO.ID_CLIENTE
GROUP BY TAB_CLIENTE.NOME_CLIENTE
ORDER BY SUM(TAB_PEDIDO.QT_PRODUTO) DESC;