SELECT TAB_CLIENTE.ID_CLIENTE, TAB_CLIENTE.NOME_CLIENTE, TAB_PEDIDO.QT_PRODUTO
FROM TAB_CLIENTE
FULL OUTER JOIN TAB_PEDIDO
ON TAB_CLIENTE.ID_CLIENTE = TAB_PEDIDO.ID_CLIENTE
WHERE QT_PRODUTO IS NULL;