-- Exercício 1
SELECT NOME_CLIENTE FROM TAB_CLIENTE;

-- Exercício 2
SELECT MAX(VALOR_PRODUTO) FROM TAB_PRODUTO;

-- Exercício 3
SELECT TAB_CLIENTE.ID_CLIENTE, TAB_CLIENTE.NOME_CLIENTE, TAB_PEDIDO.QT_PRODUTO
FROM TAB_CLIENTE
FULL OUTER JOIN TAB_PEDIDO
ON TAB_CLIENTE.ID_CLIENTE = TAB_PEDIDO.ID_CLIENTE
WHERE QT_PRODUTO IS NULL;

-- Exercício 4
SELECT TAB_CLIENTE.NOME_CLIENTE, SUM(TAB_PEDIDO.QT_PRODUTO)
FROM TAB_CLIENTE
ON TAB_CLIENTE.ID_CLIENTE = TAB_PEDIDO.ID_CLIENTE
GROUP BY TAB_CLIENTE.NOME_CLIENTE
ORDER BY SUM(TAB_PEDIDO.QT_PRODUTO) DESC;

--Incompleto