--Exercício 2 - Criando as tabelas
CREATE TABLE Alunos (
    MAT NUMBER,
    NOME VARCHAR2(100),
    ENDEREÇO VARCHAR2(200),
    CIDADE VARCHAR2(100),
    PRIMARY KEY (MAT)
);
/
CREATE TABLE Disciplinas (
    COD_DISC NUMBER,
    NOME_DISC VARCHAR2(100),
    CARGA_HORA NUMBER,
    PRIMARY KEY (COD_DISC)
);
/
CREATE TABLE Professores (
    COD_PROF NUMBER,
    NOME VARCHAR2(100),
    ENDEREÇO VARCHAR2(200),
    CIDADE VARCHAR2(100),
    PRIMARY KEY (COD_PROF)
);
/
CREATE TABLE Turma (
    COD_TURMA INT,
    ANO INT,
    HORARIO VARCHAR2(7),
    COD_DISC INT,
    COD_PROF INT,
    PRIMARY KEY(COD_TURMA, ANO, COD_DISC, COD_PROF),
    CONSTRAINT FK_DisciplinasTurma
        FOREIGN KEY(COD_DISC)
        REFERENCES Disciplinas(COD_DISC),
    CONSTRAINT FK_ProfessoresTurma
        FOREIGN KEY(COD_PROF)
        REFERENCES Professores(COD_PROF)   
);
/
CREATE TABLE Historico(
    FREQUENCIA decimal(5,2),
    CHECK (FREQUENCIA <= 100.00),
    NOTA DECIMAL(5,2),
    CHECK (NOTA <= 100.00),
    COD_TURMA INT,
    ANO INT,
    COD_DISC INT,
    COD_PROF INT,
    CONSTRAINT FK_TurmaHistorico
        FOREIGN KEY(COD_TURMA, ANO, COD_DISC, COD_PROF)
        REFERENCES Turma(COD_TURMA, ANO, COD_DISC, COD_PROF)
);

--Exercício 2 - Inserindo os registros
INSERT INTO Alunos (MAT, NOME, ENDEREÇO, CIDADE) 
VALUES ('2015010101', 'JOSE DE ALENCAR', 'RUA DAS ALMAS', 'NATAL');

INSERT INTO Alunos (MAT, NOME, ENDEREÇO, CIDADE) 
VALUES ('2015010102', 'JOÃO JOSÉ', 'AVENIDA RUY CARNEIRO', 'JOÃO PESSOA');

INSERT INTO Alunos (MAT, NOME, ENDEREÇO, CIDADE) 
VALUES ('2015010103', 'MARIA JOAQUINA', 'RUA CARROSSEL', 'RECIFE');

INSERT INTO Alunos (MAT, NOME, ENDEREÇO, CIDADE) 
VALUES ('2015010104', 'MARIA DAS DORES', 'RUA DAS LADEIRAS', 'FORTALEZA');

INSERT INTO Alunos (MAT, NOME, ENDEREÇO, CIDADE) 
VALUES ('2015010105', 'JOSUÉ CLAUDINO DOS SANTOS', 'CENTRO', 'NATAL');

INSERT INTO Alunos (MAT, NOME, ENDEREÇO, CIDADE) 
VALUES ('2015010106', 'JOSUÉLISSON CLAUDINO DOS SANTOS', 'CENTRO', 'NATAL');

COMMIT;

--Em andamento




