--Exercício 1 - Criando a tabela
CREATE TABLE TAB_PEDIDO(  
    ID_NF INT,  
    ID_ITEM INT,  
    COD_PRODUTO INT,  
    VALOR_UNIT FLOAT,  
    QUANTIDADE NUMBER, 
    DESCONTO FLOAT  
);

--Inserindo os dados
INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (1, 1, 1, 25.00, 10, 5);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (1, 2, 2, 13.50, 3, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (1, 3, 3, 15.00, 2, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (1, 4, 4, 10.00, 1, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (1, 5, 5, 30.00, 1, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (2, 1, 3, 15.00, 4, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (2, 2, 4, 10.00, 5, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (2, 3, 5, 30.00, 7, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (3, 1, 1, 25.00, 5, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (3, 2, 4, 10.00, 4, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (3, 3, 5, 30.00, 5, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (3, 4, 2, 13.50, 7, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (4, 1, 5, 30.00, 10, 15);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (4, 2, 4, 10.00, 12, 5);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (4, 3, 1, 25.00, 13, 5);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (4, 4, 2, 13.50, 15, 5);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (5, 1, 3, 15.00, 3, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (5, 2, 5, 30.00, 6, NULL);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (6, 1, 1, 25.00, 22, 15);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (6, 2, 3, 15.00, 25, 20);


INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (7, 1, 1, 25.00, 10, 3);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (7, 2, 2, 13.50, 10, 4);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (7, 3, 3, 15.00, 10, 4);

INSERT INTO TAB_PEDIDO (ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (7, 4, 5, 30.00, 10, 1);

--Exercício 1 - a)
SELECT ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT FROM TAB_PEDIDO WHERE DESCONTO IS NULL;

--Exercício 1 - b)
SELECT ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, (VALOR_UNIT*(DESCONTO/100)) 
FROM TAB_PEDIDO 
WHERE DESCONTO IS NOT NULL;

--Exercício 1 - c)
UPDATE TAB_PEDIDO SET DESCONTO = 0
WHERE DESCONTO IS NULL; 

--Exercício 1 - d)
SELECT ID_NF, ID_ITEM, COD_PRODUTO, VALOR_UNIT, (QUANTIDADE *
VALOR_UNIT) AS VALOR_TOTAL, DESCONTO, (VALOR_UNIT*(DESCONTO/100)) AS VALOR_VENDIDO
FROM TAB_PEDIDO;

--Exercício 1 - e)
SELECT SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL
FROM TAB_PEDIDO
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

--Exercício 1 - f)
SELECT ID_NF, SUM(VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100))) AS VALOR_VENDIDO
FROM TAB_PEDIDO
GROUP BY ID_NF
ORDER BY VALOR_VENDIDO DESC;

--Exercício 1 - g)
SELECT COD_PRODUTO, SUM(QUANTIDADE)
FROM TAB_PEDIDO
GROUP BY COD_PRODUTO;

--Exercício 1 - h)
SELECT ID_NF, COD_PRODUTO, QUANTIDADE
FROM TAB_PEDIDO
WHERE QUANTIDADE > 10
GROUP BY ID_NF, COD_PRODUTO; -- só da certo se tiver QUANTIDADE

--Exercício 1 - i)
SELECT ID_NF, SUM(VALOR_UNIT * QUANTIDADE) AS VALOR_TOTAL 
FROM TAB_PEDIDO 
HAVING SUM(VALOR_UNIT * QUANTIDADE) > 500
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

--Exercício 1 - j)
SELECT COD_PROD, AVG(DESCONTO) AS MEDIA
FROM TAB_PEDIDO
GROUP BY COD_PRODUTO;

--Exercício 1 - k)
SELECT COD_PRODUTO, MIN(DESCONTO) AS MENOR, MAX(DESCONTO) AS MAIOR, AVG(DESCONTO) AS MEDIA
FROM TAB_PEDIDO
GROUP BY COD_PRODUTO;

--Exercício 1 - l)
SELECT ID_NF, COUNT(ID_ITEM) AS QTD_ITENS
FROM TAB_PEDIDO
HAVING COUNT(ID_ITEM) > 3
GROUP BY ID_NF;

